### ISSUE TITLE
设置实体后再关联其他查询条件生成没有用and关联

### ISSUE THREAD

**Issue by davidwangmb** [bobo667/mybatis-plus-join#4]
![image](https://user-images.githubusercontent.com/9404625/203198224-60f10700-754c-483e-9e3e-4159efa70549.png)
![image](https://user-images.githubusercontent.com/9404625/203198668-680ca6db-b026-49f1-9586-52ecf43c4d9c.png)

**Comment by 2335662257** [comment]
哈哈哈，唯一一个open的issue，还是隔壁的

**Comment by bobo667** [comment]
> 哈哈哈，唯一一个open的issue，还是隔壁的

github上不多，一般都在gitee上
