### ISSUE TITLE
希望指定别名可以用lambda表达式,同一个表join多次报错：Not unique table/alias

### ISSUE THREAD

**Issue by 2335662257** [bobo667/mybatis-plus-join#5]
1. 指定字段的别名使用lambda表达式，而不是使用字符串
类似这样：
.selectAs(UserAddressDO::getAddress, UserDTO::getUserAddress)

2. 同一个表多次join或报错： Not unique table/alias

**Comment by bobo667** [comment]
> * 指定字段的别名使用lambda表达式，而不是使用字符串
>   类似这样：
>   .selectAs(UserAddressDO::getAddress, UserDTO::getUserAddress)
> * 同一个表多次join或报错： Not unique table/alias

第一个那个，有的时候人家的返回类型是map，这样map没法搞，
至于第二个这个问题，我倒是知道相同表关联还是写SQL吧

**Comment by 2335662257** [comment]
> 

第一个我觉得可以加一个重载的方法

**Comment by bobo667** [comment]
> > > * 指定字段的别名使用lambda表达式，而不是使用字符串
> > >   类似这样：
> > >   .selectAs(UserAddressDO::getAddress, UserDTO::getUserAddress)
> > > * 同一个表多次join或报错： Not unique table/alias
> > 
> > 
> > 第一个那个，有的时候人家的返回类型是map，这样map没法搞， 至于第二个这个问题，我倒是知道相同表关联还是写SQL吧
> 
> 第一个我觉得可以加一个重载的方法

怎么说呢，总感觉会让人误会以为是查询字段，我想想吧

**Comment by bobo667** [comment]
> * 指定字段的别名使用lambda表达式，而不是使用字符串
>   类似这样：
>   .selectAs(UserAddressDO::getAddress, UserDTO::getUserAddress)
> * 同一个表多次join或报错： Not unique table/alias

最新版本，.selectAs(UserAddressDO::getAddress, UserDTO::getUserAddress)这个加上了，selectAs(SFunction<T, ?> column, SFunction<J, ?> alias) 和 selectAs#addFunAlias
